# Generated by scripts/render-homebrew-formula.sh in DanielCardonaRojas/codemark.
# Do not edit by hand; re-run the release flow to regenerate.
#
# Ships precompiled binaries for both `codemark` (codemark-cli) and
# `codemark-tui` (codemark-tui) so a single install provides the CLI and the
# TUI that `codemark tui` shells out to.
class Codemark < Formula
  desc "A structural bookmarking system for code using tree-sitter queries"
  homepage "https://github.com/DanielCardonaRojas/codemark"
  version "0.7.15"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-cli-aarch64-apple-darwin.tar.xz"
      sha256 "a241d683f35bcd6592fdb3e4939a728485ab7ff5b7e2208e2f572da7701d03aa"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-tui-aarch64-apple-darwin.tar.xz"
        sha256 "9c974ad08043f5351731e5f575fa89f10dd9cbaa6fa01ed21001361e846a163e"
      end
    end

    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-cli-x86_64-apple-darwin.tar.xz"
      sha256 "479ce3df3ab0f7bdc7cda558688cb52e00a4afb998d0c488850c8e48460d3482"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-tui-x86_64-apple-darwin.tar.xz"
        sha256 "a288ca761d94fe9329a321076c8e098fb3093f34a7e817b8a5faa540d1e8f13f"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "66a0703d6bfb010a1a3583d0cc495182762815e8b0742158e959278133a5f017"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.15/codemark-tui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "0943ff1ae0782139a381ad441c884d719643f5d0eb1aca42e4f0c4a4bb3a6304"
      end
    end
  end

  def install
    bin.install "codemark"
    resource("codemark-tui").stage do
      bin.install "codemark-tui"
    end
  end

  test do
    assert_match "codemark", shell_output("#{bin}/codemark --version")
    # codemark-tui has no --version flag (an unknown arg just launches the TUI,
    # which needs a TTY). --list-schemes prints headlessly and exits 0, so it's
    # the right smoke test for the bundled binary.
    system bin/"codemark-tui", "--list-schemes"
  end
end
