# Generated by scripts/render-homebrew-formula.sh in DanielCardonaRojas/codemark.
# Do not edit by hand; re-run the release flow to regenerate.
#
# Ships precompiled binaries for both `codemark` (codemark-cli) and
# `codemark-tui` (codemark-tui) so a single install provides the CLI and the
# TUI that `codemark tui` shells out to.
class Codemark < Formula
  desc "A structural bookmarking system for code using tree-sitter queries"
  homepage "https://github.com/DanielCardonaRojas/codemark"
  version "0.7.18"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-cli-aarch64-apple-darwin.tar.xz"
      sha256 "81e1a33ed09698372294c22222e69747385781d6a101253b364fc44598496f34"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-tui-aarch64-apple-darwin.tar.xz"
        sha256 "c37dade6b91b98febc2144e082402e350685458d648045dabb63be49179b6611"
      end
    end

    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-cli-x86_64-apple-darwin.tar.xz"
      sha256 "3b83b72ac09ed64e8c7763253c6fe3eb9bd8fa38ec7b81ebf17788a84fd83f87"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-tui-x86_64-apple-darwin.tar.xz"
        sha256 "200856940870747182f9e00fdf092897cefcddbd47cd6e5303826dbd483387cd"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "5c1a62180d03fa5eb7b01b2fda90813de4d823acbf6867b4991b5e801d65e810"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.18/codemark-tui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "a15d0ff1fe67212f811e14387be8d209a79434d2b3ae6a051129d16037be2006"
      end
    end
  end

  def install
    bin.install "codemark"
    resource("codemark-tui").stage do
      bin.install "codemark-tui"
    end
  end

  test do
    assert_match "codemark", shell_output("#{bin}/codemark --version")
    # codemark-tui has no --version flag (an unknown arg just launches the TUI,
    # which needs a TTY). --list-schemes prints headlessly and exits 0, so it's
    # the right smoke test for the bundled binary.
    system bin/"codemark-tui", "--list-schemes"
  end
end
