# Generated by scripts/render-homebrew-formula.sh in DanielCardonaRojas/codemark.
# Do not edit by hand; re-run the release flow to regenerate.
#
# Ships precompiled binaries for both `codemark` (codemark-cli) and
# `codemark-tui` (codemark-tui) so a single install provides the CLI and the
# TUI that `codemark tui` shells out to.
class Codemark < Formula
  desc "A structural bookmarking system for code using tree-sitter queries"
  homepage "https://github.com/DanielCardonaRojas/codemark"
  version "0.7.19"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-cli-aarch64-apple-darwin.tar.xz"
      sha256 "05147880fe8c9aa58996a6abd7462affc6bcbb23acea1b71c1549e119c6b907a"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-tui-aarch64-apple-darwin.tar.xz"
        sha256 "2e3293318dde457dd2b7bc362465dc0a0323200ae9fd234cc7b9bf9ae95043df"
      end
    end

    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-cli-x86_64-apple-darwin.tar.xz"
      sha256 "fe2c87a454420666f95367e3d46c56ea7251fc43d3aae6592d5f2e4e4bc54ee0"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-tui-x86_64-apple-darwin.tar.xz"
        sha256 "d67d32501a569aee2eac61e5fd6085477f7b98376e2499793b60e92205c55c2c"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "bd6d3c20bf3b0a5ddc4aca3c0a3380e5779630d0cd1d05b7dd4c200f5cee5084"

      resource "codemark-tui" do
        url "https://github.com/DanielCardonaRojas/codemark/releases/download/0.7.19/codemark-tui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "51299318dade654347ca9e86009218f44ebb9644a7059838f4a80b4765a40a11"
      end
    end
  end

  def install
    bin.install "codemark"
    resource("codemark-tui").stage do
      bin.install "codemark-tui"
    end
  end

  test do
    assert_match "codemark", shell_output("#{bin}/codemark --version")
    # codemark-tui has no --version flag (an unknown arg just launches the TUI,
    # which needs a TTY). --list-schemes prints headlessly and exits 0, so it's
    # the right smoke test for the bundled binary.
    system bin/"codemark-tui", "--list-schemes"
  end
end
